import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import studentsRouter from "./students";
import consultantsRouter from "./consultants";
import universitiesRouter from "./universities";
import programsRouter from "./programs";
import countriesRouter from "./countries";
import applicationsRouter from "./applications";
import documentsRouter from "./documents";
import storageRouter from "./storage";
import shortlistsRouter from "./shortlists";
import supportRouter from "./support";
import loyaltyRouter from "./loyalty";
import testScoresRouter from "./test_scores";
import leadsRouter from "./leads";
import counsellingRouter from "./counselling";
import sopRouter from "./sop";
import teamRouter from "./team";
import partnersRouter from "./partners";
import brandingRouter from "./branding";
import assessmentRouter from "./assessment";
import coursesRouter from "./courses";
import jobsRouter from "./jobs";
import careersRouter from "./careers";
import subscriptionsRouter from "./subscriptions";
import commerceRouter from "./commerce";
import forexRouter from "./forex";
import invoicingRouter from "./invoicing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(studentsRouter);
router.use(consultantsRouter);
router.use(universitiesRouter);
router.use(programsRouter);
router.use(countriesRouter);
router.use(applicationsRouter);
router.use(documentsRouter);
router.use(storageRouter);
router.use(shortlistsRouter);
router.use(supportRouter);
router.use(loyaltyRouter);
router.use(testScoresRouter);
router.use(leadsRouter);
router.use(counsellingRouter);
router.use(sopRouter);
router.use(teamRouter);
router.use(partnersRouter);
router.use(brandingRouter);
router.use(assessmentRouter);
router.use(coursesRouter);
router.use(jobsRouter);
router.use(careersRouter);
router.use(subscriptionsRouter);
router.use(commerceRouter);
router.use(forexRouter);
router.use(invoicingRouter);

export default router;
