import type { Country, Program, University } from "@workspace/api-client-react";

const createdAt = "2026-05-21T00:00:00.000Z";
export const DEMO_APPLICATION_STORAGE_KEY = "eleevate.ai.applications.v2";

export const DEMO_COUNTRIES: Country[] = [
  {
    code: "CA",
    name: "Canada",
    flagEmoji: "🇨🇦",
    continent: "North America",
    currency: "CAD",
    visaInfo: "Study permit route with clear proof of funds, GIC planning, and post-graduation work permit pathways.",
    avgCostOfLivingUsd: 1450,
    popularCities: ["Toronto", "Vancouver", "Montreal"],
    universityCount: 98,
  },
  {
    code: "GB",
    name: "United Kingdom",
    flagEmoji: "🇬🇧",
    continent: "Europe",
    currency: "GBP",
    visaInfo: "Student route visa with CAS, tuition deposit, financial maintenance proof, and graduate route planning.",
    avgCostOfLivingUsd: 1550,
    popularCities: ["London", "Manchester", "Edinburgh"],
    universityCount: 132,
  },
  {
    code: "US",
    name: "United States",
    flagEmoji: "🇺🇸",
    continent: "North America",
    currency: "USD",
    visaInfo: "F-1 visa pathway with I-20, SEVIS, interview readiness, sponsor documentation, and OPT/STEM OPT planning.",
    avgCostOfLivingUsd: 1900,
    popularCities: ["Boston", "New York", "San Francisco"],
    universityCount: 210,
  },
  {
    code: "AU",
    name: "Australia",
    flagEmoji: "🇦🇺",
    continent: "Oceania",
    currency: "AUD",
    visaInfo: "Subclass 500 planning with GTE/GS narrative, OSHC, financial evidence, and post-study work options.",
    avgCostOfLivingUsd: 1650,
    popularCities: ["Sydney", "Melbourne", "Brisbane"],
    universityCount: 43,
  },
  {
    code: "DE",
    name: "Germany",
    flagEmoji: "🇩🇪",
    continent: "Europe",
    currency: "EUR",
    visaInfo: "Student visa route with blocked account planning, APS where relevant, language readiness, and low-tuition options.",
    avgCostOfLivingUsd: 1150,
    popularCities: ["Berlin", "Munich", "Frankfurt"],
    universityCount: 116,
  },
  {
    code: "NL",
    name: "Netherlands",
    flagEmoji: "🇳🇱",
    continent: "Europe",
    currency: "EUR",
    visaInfo: "MVV/residence permit route usually coordinated by the university after admission and proof of funds.",
    avgCostOfLivingUsd: 1450,
    popularCities: ["Amsterdam", "Delft", "Rotterdam"],
    universityCount: 54,
  },
  {
    code: "SG",
    name: "Singapore",
    flagEmoji: "🇸🇬",
    continent: "Asia",
    currency: "SGD",
    visaInfo: "Student Pass pathway with institution sponsorship, finance proof, and strong employability alignment.",
    avgCostOfLivingUsd: 1800,
    popularCities: ["Singapore City"],
    universityCount: 31,
  },
  {
    code: "IE",
    name: "Ireland",
    flagEmoji: "🇮🇪",
    continent: "Europe",
    currency: "EUR",
    visaInfo: "Stamp 2 visa route with tuition receipt, living expense proof, insurance, and graduate stay-back planning.",
    avgCostOfLivingUsd: 1500,
    popularCities: ["Dublin", "Galway", "Cork"],
    universityCount: 28,
  },
];

export const DEMO_UNIVERSITIES: University[] = [
  {
    id: "demo-uoft",
    name: "University of Toronto",
    country: "Canada",
    city: "Toronto",
    ranking: 21,
    website: "https://www.utoronto.ca",
    description: "A global research university with strong computer science, data, business, health, and engineering pathways for ambitious international students.",
    acceptanceRate: 43,
    avgTuitionUsd: 46000,
    featured: true,
    programCount: 168,
    createdAt,
  },
  {
    id: "demo-ubc",
    name: "University of British Columbia",
    country: "Canada",
    city: "Vancouver",
    ranking: 34,
    website: "https://www.ubc.ca",
    description: "A highly international Canadian university known for research, sustainability, co-op pathways, and strong graduate outcomes on the west coast.",
    acceptanceRate: 52,
    avgTuitionUsd: 42000,
    featured: true,
    programCount: 131,
    createdAt,
  },
  {
    id: "demo-manchester",
    name: "University of Manchester",
    country: "United Kingdom",
    city: "Manchester",
    ranking: 32,
    website: "https://www.manchester.ac.uk",
    description: "A Russell Group university with strong employability, a broad course catalogue, and excellent links into technology, business, and research.",
    acceptanceRate: 56,
    avgTuitionUsd: 36000,
    featured: true,
    programCount: 142,
    createdAt,
  },
  {
    id: "demo-leeds",
    name: "University of Leeds",
    country: "United Kingdom",
    city: "Leeds",
    ranking: 75,
    website: "https://www.leeds.ac.uk",
    description: "A practical, student-friendly UK option with strong business, engineering, media, and data programs, plus good value outside London.",
    acceptanceRate: 64,
    avgTuitionUsd: 31000,
    featured: true,
    programCount: 118,
    createdAt,
  },
  {
    id: "demo-asu",
    name: "Arizona State University",
    country: "United States",
    city: "Tempe",
    ranking: 179,
    website: "https://www.asu.edu",
    description: "A large innovation-focused US university with flexible entry routes, strong technology programs, scholarships, and career services.",
    acceptanceRate: 88,
    avgTuitionUsd: 34000,
    featured: true,
    programCount: 280,
    createdAt,
  },
  {
    id: "demo-northeastern",
    name: "Northeastern University",
    country: "United States",
    city: "Boston",
    ranking: 375,
    website: "https://www.northeastern.edu",
    description: "A co-op driven university for students who want work-integrated learning, tech careers, analytics, business, and strong US employer exposure.",
    acceptanceRate: 7,
    avgTuitionUsd: 60000,
    featured: true,
    programCount: 190,
    createdAt,
  },
  {
    id: "demo-melbourne",
    name: "University of Melbourne",
    country: "Australia",
    city: "Melbourne",
    ranking: 14,
    website: "https://www.unimelb.edu.au",
    description: "Australia's leading research university with global recognition, broad graduate pathways, and a strong professional network.",
    acceptanceRate: 70,
    avgTuitionUsd: 43000,
    featured: true,
    programCount: 156,
    createdAt,
  },
  {
    id: "demo-monash",
    name: "Monash University",
    country: "Australia",
    city: "Melbourne",
    ranking: 42,
    website: "https://www.monash.edu",
    description: "A highly practical Australian university with strong STEM, business, pharmacy, and employability pathways across multiple campuses.",
    acceptanceRate: 40,
    avgTuitionUsd: 39000,
    featured: true,
    programCount: 150,
    createdAt,
  },
  {
    id: "demo-tum",
    name: "Technical University of Munich",
    country: "Germany",
    city: "Munich",
    ranking: 37,
    website: "https://www.tum.de",
    description: "A top European technology university with excellent engineering, AI, management, and applied science pathways at comparatively low tuition.",
    acceptanceRate: 8,
    avgTuitionUsd: 9000,
    featured: true,
    programCount: 118,
    createdAt,
  },
  {
    id: "demo-delft",
    name: "Delft University of Technology",
    country: "Netherlands",
    city: "Delft",
    ranking: 47,
    website: "https://www.tudelft.nl",
    description: "A specialist technology university for engineering, design, architecture, data, and sustainability-focused graduate routes.",
    acceptanceRate: 65,
    avgTuitionUsd: 23000,
    featured: true,
    programCount: 64,
    createdAt,
  },
  {
    id: "demo-nus",
    name: "National University of Singapore",
    country: "Singapore",
    city: "Singapore City",
    ranking: 8,
    website: "https://www.nus.edu.sg",
    description: "A leading Asian university with elite computer science, business, public policy, and research pathways connected to regional employers.",
    acceptanceRate: 10,
    avgTuitionUsd: 31000,
    featured: true,
    programCount: 125,
    createdAt,
  },
  {
    id: "demo-trinity",
    name: "Trinity College Dublin",
    country: "Ireland",
    city: "Dublin",
    ranking: 81,
    website: "https://www.tcd.ie",
    description: "A historic university in Dublin with strong computer science, business, humanities, and post-study work opportunities in Ireland's tech economy.",
    acceptanceRate: 34,
    avgTuitionUsd: 29000,
    featured: true,
    programCount: 94,
    createdAt,
  },
];

export const DEMO_PROGRAMS: Program[] = [
  {
    id: "demo-uoft-mscs",
    universityId: "demo-uoft",
    name: "MSc Computer Science",
    degree: "master",
    field: "Computer Science",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 46000,
    applicationDeadline: "2026-06-03",
    startDate: "2026-09-01",
    ieltsRequirement: 7,
    toeflRequirement: 100,
    gpaRequirement: 3.3,
    description: "Research-led graduate pathway for AI, software systems, data, and human-computer interaction.",
    university: DEMO_UNIVERSITIES[0],
    createdAt,
  },
  {
    id: "demo-uoft-mba",
    universityId: "demo-uoft",
    name: "Rotman MBA",
    degree: "mba",
    field: "Business",
    duration: 20,
    durationUnit: "months",
    tuitionUsd: 58000,
    applicationDeadline: "2026-05-30",
    startDate: "2026-09-01",
    ieltsRequirement: 7,
    toeflRequirement: 100,
    gpaRequirement: 3.2,
    university: DEMO_UNIVERSITIES[0],
    createdAt,
  },
  {
    id: "demo-ubc-data",
    universityId: "demo-ubc",
    name: "Master of Data Science",
    degree: "master",
    field: "Data Science",
    duration: 10,
    durationUnit: "months",
    tuitionUsd: 42000,
    applicationDeadline: "2026-04-30",
    startDate: "2026-09-01",
    ieltsRequirement: 7,
    toeflRequirement: 100,
    gpaRequirement: 3.2,
    university: DEMO_UNIVERSITIES[1],
    createdAt,
  },
  {
    id: "demo-manchester-ai",
    universityId: "demo-manchester",
    name: "MSc Artificial Intelligence",
    degree: "master",
    field: "Artificial Intelligence",
    duration: 12,
    durationUnit: "months",
    tuitionUsd: 36000,
    applicationDeadline: "2026-07-01",
    startDate: "2026-09-15",
    ieltsRequirement: 6.5,
    toeflRequirement: 90,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[2],
    createdAt,
  },
  {
    id: "demo-leeds-business",
    universityId: "demo-leeds",
    name: "MSc International Business",
    degree: "master",
    field: "Business",
    duration: 12,
    durationUnit: "months",
    tuitionUsd: 31000,
    applicationDeadline: "2026-06-28",
    startDate: "2026-09-15",
    ieltsRequirement: 6.5,
    toeflRequirement: 88,
    gpaRequirement: 2.8,
    university: DEMO_UNIVERSITIES[3],
    createdAt,
  },
  {
    id: "demo-asu-software",
    universityId: "demo-asu",
    name: "MS Software Engineering",
    degree: "master",
    field: "Software Engineering",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 34000,
    applicationDeadline: "2026-05-15",
    startDate: "2026-08-20",
    ieltsRequirement: 6.5,
    toeflRequirement: 80,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[4],
    createdAt,
  },
  {
    id: "demo-northeastern-analytics",
    universityId: "demo-northeastern",
    name: "MS Analytics",
    degree: "master",
    field: "Analytics",
    duration: 18,
    durationUnit: "months",
    tuitionUsd: 60000,
    applicationDeadline: "2026-06-01",
    startDate: "2026-09-01",
    ieltsRequirement: 7,
    toeflRequirement: 100,
    gpaRequirement: 3.1,
    university: DEMO_UNIVERSITIES[5],
    createdAt,
  },
  {
    id: "demo-melbourne-is",
    universityId: "demo-melbourne",
    name: "Master of Information Systems",
    degree: "master",
    field: "Information Systems",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 43000,
    applicationDeadline: "2026-05-31",
    startDate: "2026-07-22",
    ieltsRequirement: 6.5,
    toeflRequirement: 79,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[6],
    createdAt,
  },
  {
    id: "demo-monash-cyber",
    universityId: "demo-monash",
    name: "Master of Cybersecurity",
    degree: "master",
    field: "Cybersecurity",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 39000,
    applicationDeadline: "2026-06-15",
    startDate: "2026-07-22",
    ieltsRequirement: 6.5,
    toeflRequirement: 79,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[7],
    createdAt,
  },
  {
    id: "demo-tum-ai",
    universityId: "demo-tum",
    name: "MSc Data Engineering and Analytics",
    degree: "master",
    field: "Data Engineering",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 9000,
    applicationDeadline: "2026-05-31",
    startDate: "2026-10-01",
    ieltsRequirement: 6.5,
    toeflRequirement: 88,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[8],
    createdAt,
  },
  {
    id: "demo-delft-design",
    universityId: "demo-delft",
    name: "MSc Strategic Product Design",
    degree: "master",
    field: "Design",
    duration: 24,
    durationUnit: "months",
    tuitionUsd: 23000,
    applicationDeadline: "2026-04-01",
    startDate: "2026-09-01",
    ieltsRequirement: 7,
    toeflRequirement: 100,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[9],
    createdAt,
  },
  {
    id: "demo-nus-cs",
    universityId: "demo-nus",
    name: "Master of Computing",
    degree: "master",
    field: "Computer Science",
    duration: 18,
    durationUnit: "months",
    tuitionUsd: 31000,
    applicationDeadline: "2026-03-15",
    startDate: "2026-08-01",
    ieltsRequirement: 6.5,
    toeflRequirement: 90,
    gpaRequirement: 3.4,
    university: DEMO_UNIVERSITIES[10],
    createdAt,
  },
  {
    id: "demo-trinity-business",
    universityId: "demo-trinity",
    name: "MSc Digital Marketing Strategy",
    degree: "master",
    field: "Marketing",
    duration: 12,
    durationUnit: "months",
    tuitionUsd: 29000,
    applicationDeadline: "2026-06-30",
    startDate: "2026-09-01",
    ieltsRequirement: 6.5,
    toeflRequirement: 88,
    gpaRequirement: 3,
    university: DEMO_UNIVERSITIES[11],
    createdAt,
  },
];

export function getDemoUniversity(id: string | undefined): University | undefined {
  if (!id) return undefined;
  return DEMO_UNIVERSITIES.find((university) => university.id === id);
}

export function getDemoProgramsForUniversity(universityId: string | undefined): Program[] {
  if (!universityId) return [];
  return DEMO_PROGRAMS.filter((program) => program.universityId === universityId);
}

export function getCountryCodesForName(name: string): string[] {
  return DEMO_COUNTRIES.filter((country) => country.name === name).map((country) => country.code);
}
